Repository OUCH-cs/CAPSTONE-PWA, pull requests merged in 2025-06, with the labels that each got.

#44 [FE-81] 홈 및 자가진단표 다국어 처리 및 로직 수정
  src/features/diagnosis/diagnosis.type.ts
  src/features/diagnosis/lib/useConditionStep.ts
  src/features/diagnosis/lib/useSymptomsList.ts
  src/features/diagnosis/lib/useSystemList.ts
  src/features/diagnosis/ui/DiagnosisHeader.tsx
  src/features/diagnosis/ui/pages/StepFour.tsx
  src/features/diagnosis/ui/pages/StepOne.tsx
  src/features/diagnosis/ui/pages/StepSix.tsx
  src/features/i18n/locales/en-US/translation.json
  src/features/i18n/locales/ko-KR/translation.json
  src/features/i18n/locales/zh-CN/translation.json
  src/features/main/lib/useGuide.ts
  src/features/main/lib/useGuideCategories.ts
  src/features/main/service/guideAtoms.ts
  src/features/main/ui/DiagnosisCard.tsx
  src/features/main/ui/GuideHeader.tsx
  src/features/main/ui/GuideQuestions.tsx
  src/features/main/ui/MainHeader.tsx
  src/pages/main/guide/guide.tsx
  src/pages/main/self-diagnosis/RecommendPage.tsx
Labels: ✨ Feature

#47 [FE-87]자가진단 condition 값 조회 에러 해결
  src/features/diagnosis/diagnosis.type.ts
  src/features/diagnosis/lib/useConditionStep.ts
  src/features/diagnosis/ui/pages/StepConditions.tsx
  src/features/diagnosis/ui/pages/StepFive.tsx
  src/features/i18n/locales/en-US/translation.json
  src/features/i18n/locales/ko-KR/translation.json
  src/features/i18n/locales/zh-CN/translation.json
Labels: 🐞 BugFix

#51 [FE-89] 추천페이지 UI 수정
  src/app/routes/Routes.tsx
  src/features/i18n/locales/en-US/translation.json
  src/features/i18n/locales/ko-KR/translation.json
  src/features/i18n/locales/zh-CN/translation.json
  src/features/main/ui/MainHeader.tsx
  src/pages/index.ts
  src/pages/main/commingsoon.tsx
  src/pages/main/mainpage.tsx
  src/pages/main/self-diagnosis/RecommendPage.tsx
Labels: 🔨 Refactor

#52 [FE-91] 통역 로직 및 ui 개선
  src/entities/translate/ui/GuideRoutingButton.tsx
  src/entities/translate/ui/MessageBubble.tsx
  src/entities/translate/ui/MuteToggleButton.tsx
  src/entities/translate/ui/Profile.tsx
  src/entities/translate/ui/TranslateMicIndicator.tsx
  src/entities/translate/ui/TranslateSessionHeader.tsx
  src/entities/translate/ui/TranslateSessionOption.tsx
  src/features/translate/lib/promptUpdate.ts
  src/features/translate/translate.consts.ts
  src/features/translate/translate.types.ts
  src/features/translate/ui/RecordingIndicator.tsx
  src/features/translate/ui/TranslateController.tsx
  src/features/translate/ui/TranslateSessionView.tsx
  src/features/translate/ui/chat/ChatView.tsx
  src/features/translate/ui/modal/FinishTranslationModal.tsx
  src/features/translate/ui/modal/LoadingModal.tsx
  src/shared/assets/translate/doctor.svg
  src/shared/components/loading/BouncingLoadingDots.tsx
  vite.config.ts
Labels: 🔨 Refactor

#53 [develop -> main]
  src/app/routes/Routes.tsx
  src/entities/translate/ui/GuideRoutingButton.tsx
  src/entities/translate/ui/MessageBubble.tsx
  src/entities/translate/ui/MuteToggleButton.tsx
  src/entities/translate/ui/Profile.tsx
  src/entities/translate/ui/TranslateMicIndicator.tsx
  src/entities/translate/ui/TranslateSessionHeader.tsx
  src/entities/translate/ui/TranslateSessionOption.tsx
  src/features/i18n/locales/en-US/translation.json
  src/features/i18n/locales/ko-KR/translation.json
  src/features/i18n/locales/zh-CN/translation.json
  src/features/main/ui/MainHeader.tsx
  src/features/mypage/MyPage.constants.ts
  src/features/mypage/ui/Bottom.tsx
  src/features/mypage/ui/EditForm.tsx
  src/features/mypage/ui/Header.tsx
  src/features/mypage/ui/LanguageAccordion.tsx
  src/features/translate/lib/promptUpdate.ts
  src/features/translate/translate.consts.ts
  src/features/translate/translate.types.ts
  src/features/translate/ui/RecordingIndicator.tsx
  src/features/translate/ui/TranslateController.tsx
  src/features/translate/ui/TranslateSessionView.tsx
  src/features/translate/ui/chat/ChatView.tsx
  src/features/translate/ui/modal/FinishTranslationModal.tsx
  src/features/translate/ui/modal/LoadingModal.tsx
  src/pages/index.ts
  src/pages/main/commingsoon.tsx
  src/pages/main/mainpage.tsx
  src/pages/main/self-diagnosis/RecommendPage.tsx
  src/pages/mypage/edit-profile.tsx
  src/pages/mypage/mypage.tsx
  src/shared/assets/translate/doctor.svg
  src/shared/components/loading/BouncingLoadingDots.tsx
  vite.config.ts
Labels: ✨ Feature

#54 통역 중국어 추가 [develop -> main]
  src/features/translate/lib/promptUpdate.ts
  src/features/translate/translate.consts.ts
  src/features/translate/ui/TranslateController.tsx
Labels: :earth_asia: Deploy

#58 위치 기반 확인 통역 모달 플로우 추가, 리뷰 생성 및 조회 API 연동
  src/features/i18n/locales/en-US/translation.json
  src/features/i18n/locales/ko-KR/translation.json
  src/features/i18n/locales/zh-CN/translation.json
  src/features/search/services/api/searcApi.ts
  src/features/search/types/search.types.ts
  src/features/search/ui/dropdown/DepartmentFilterDropdown.tsx
  src/features/search/ui/dropdown/RegionFilterDropdown.tsx
  src/features/search/ui/dropdown/TypeFilterDropdown.tsx
  src/features/translate/ui/TranslateController.tsx
  src/features/translate/ui/modal/FinishTranslationModal.tsx
  src/features/translate/ui/modal/LocationConfirmModal.tsx
  src/pages/search/review-form.tsx
  src/pages/search/search-detail.tsx
  src/pages/translate/translate-finish.tsx
  src/widgets/search/ReviewSection.tsx
Labels: ✨ Feature

#60 [develop -> main]
  src/features/i18n/locales/en-US/translation.json
  src/features/i18n/locales/ko-KR/translation.json
  src/features/i18n/locales/zh-CN/translation.json
  src/features/search/services/api/searcApi.ts
  src/features/search/types/search.types.ts
  src/features/search/ui/dropdown/DepartmentFilterDropdown.tsx
  src/features/search/ui/dropdown/RegionFilterDropdown.tsx
  src/features/search/ui/dropdown/TypeFilterDropdown.tsx
  src/features/translate/ui/TranslateController.tsx
  src/features/translate/ui/modal/FinishTranslationModal.tsx
  src/features/translate/ui/modal/LocationConfirmModal.tsx
  src/pages/search/review-form.tsx
  src/pages/search/search-detail.tsx
  src/pages/translate/translate-finish.tsx
  src/widgets/search/ReviewSection.tsx
Labels: :earth_asia: Deploy

#61 전사본-번역본 매핑 안되는 버그 수정
  src/features/translate/ui/TranslateController.tsx
Labels: 🔥 Hotfix

#62 [develop -> main]
  src/features/i18n/locales/en-US/translation.json
  src/features/i18n/locales/ko-KR/translation.json
  src/features/i18n/locales/zh-CN/translation.json
  src/features/records/ui/HealthStatusData.tsx
  src/features/translate/ui/TranslateController.tsx
  src/pages/records/medicalrecord-add.tsx
Labels: :earth_asia: Deploy

#64 통역-의료기록 요약 [develop -> main]
  src/features/translate/ui/TranslateController.tsx
Labels: :earth_asia: Deploy

#65 [FE-93] 마이페이지 리뷰 페이지 추가
  src/app/routes/Routes.tsx
  src/features/mypage/service/MyPageApi.ts
  src/features/mypage/ui/Action.tsx
  src/features/mypage/ui/Bottom.tsx
  src/features/mypage/ui/EditForm.tsx
  src/features/mypage/ui/ReviewAccordion.tsx
  src/features/mypage/ui/ReviewHeader.tsx
  src/features/records/ui/HealthStatusData.tsx
  src/features/records/ui/MedicalRecordData.tsx
  src/features/records/ui/SelfDiagnosisData.tsx
  src/pages/mypage/mypage.tsx
  src/pages/mypage/review.tsx
Labels: ✨ Feature

#66 [develop -> main]
  src/app/routes/Routes.tsx
  src/features/mypage/service/MyPageApi.ts
  src/features/mypage/ui/Action.tsx
  src/features/mypage/ui/Bottom.tsx
  src/features/mypage/ui/EditForm.tsx
  src/features/mypage/ui/ReviewAccordion.tsx
  src/features/mypage/ui/ReviewHeader.tsx
  src/features/records/ui/HealthStatusData.tsx
  src/features/records/ui/MedicalRecordData.tsx
  src/features/records/ui/SelfDiagnosisData.tsx
  src/pages/mypage/mypage.tsx
  src/pages/mypage/review.tsx
Labels: :earth_asia: Deploy
