Repository OUCH-cs/CAPSTONE-PWA, pull requests merged in 2025-05, with the labels that each got.

#18 [FE-50] 검색 기본 UI 구현
  package.json
  src/app/main.tsx
  src/app/providers/AuthGuard.tsx
  src/app/routes/Routes.tsx
  src/entities/search/ui/CategoryTag.tsx
  src/features/map/map.types.ts
  src/features/map/ui/MapContent.tsx
  src/features/search/lib/formatDistance.ts
  src/features/search/lib/getDistanceInMeters.ts
  src/features/search/search.consts.ts
  src/features/search/search.types.ts
  src/features/search/services/api/searchInstance.ts
  src/features/search/services/api/searchQuery.ts
  src/features/search/services/searchDetailPlaceQuery.ts
  src/features/search/services/store/searchQueryAtom.ts
  src/features/search/services/useNearbySearch.ts
  src/features/search/services/useTextSearch.ts
  src/features/search/ui/SearchList.tsx
  src/features/search/ui/SearchPreviewCard.tsx
  src/features/search/ui/Searchbar.tsx
  src/features/search/ui/detail/ContactFavoritePanel.tsx
  src/features/search/ui/detail/SearchDetailHeader.tsx
  src/features/search/ui/detail/SearchDetailInfo.tsx
  src/features/search/ui/index.ts
  src/features/sign-in/services/atoms/auth.atoms.ts
  src/pages/index.ts
  src/pages/map/map.tsx
  src/pages/search/search-detail.tsx
  src/pages/search/search.tsx
  src/shared/assets/search/call.svg
  src/shared/assets/search/favorite.svg
  src/shared/assets/search/search.svg
  src/shared/assets/search/star.svg
  src/shared/components/base/RootLayout.tsx
  src/shared/consts/common.ts
  src/shared/lib/getCurrLocation.ts
  src/shared/services/useCurrLocation.ts
  src/shared/types/common.ts
  yarn.lock
Labels: ✨ Feature

#21 [develop -> main]
  package.json
  src/app/main.tsx
  src/app/providers/AuthGuard.tsx
  src/app/routes/Routes.tsx
  src/entities/search/ui/CategoryTag.tsx
  src/features/map/map.types.ts
  src/features/map/ui/MapContent.tsx
  src/features/search/lib/formatDistance.ts
  src/features/search/lib/getDistanceInMeters.ts
  src/features/search/search.consts.ts
  src/features/search/search.types.ts
  src/features/search/services/api/searchInstance.ts
  src/features/search/services/api/searchQuery.ts
  src/features/search/services/api/textSearchApi.ts
  src/features/search/services/searchDetailPlaceQuery.ts
  src/features/search/services/store/filterAtom.ts
  src/features/search/services/store/searchQueryAtom.ts
  src/features/search/services/useNearbySearch.ts
  src/features/search/services/useTextSearch.ts
  src/features/search/ui/DepartmentFilterDropdown.tsx
  src/features/search/ui/SearchList.tsx
  src/features/search/ui/SearchPreviewCard.tsx
  src/features/search/ui/Searchbar.tsx
  src/features/search/ui/SortDropdown.tsx
  src/features/search/ui/detail/ContactFavoritePanel.tsx
  src/features/search/ui/detail/SearchDetailHeader.tsx
  src/features/search/ui/detail/SearchDetailInfo.tsx
  src/features/search/ui/index.ts
  src/features/sign-in/services/atoms/auth.atoms.ts
  src/pages/index.ts
  src/pages/map/map.tsx
  src/pages/search/search-detail.tsx
  src/pages/search/search.tsx
  src/shared/assets/common/arrow.svg
  src/shared/assets/search/call.svg
  src/shared/assets/search/favorite.svg
  src/shared/assets/search/search.svg
  src/shared/assets/search/star.svg
  src/shared/components/base/RootLayout.tsx
  src/shared/components/dropdown/Dropdown.tsx
  src/shared/components/dropdown/Menu.tsx
  src/shared/components/dropdown/Trigger.tsx
  src/shared/components/dropdown/index.ts
  src/shared/components/skeleton/Skeleton.tsx
  src/shared/consts/common.ts
  src/shared/lib/getCurrLocation.ts
  src/shared/lib/useClickOutside.ts
  src/shared/services/useCurrLocation.ts
  src/shared/types/common.ts
  src/shared/types/components.types.ts
  yarn.lock
Labels: :earth_asia: Deploy

#17 [FE-35] 플로팅 버튼 구현
  src/shared/assets/home/CreateDiagnosis.svg
  src/shared/assets/records/NewButton.svg
  src/shared/assets/search/MapButton.svg
  src/shared/components/button/FloatingButton.tsx
Labels: ✨ Feature

#22 [FE-57] 통역 진료 가이드 UI 구현 및 API 연동
  src/app/routes/Routes.tsx
  src/entities/translate/ui/GuideProgressBar.tsx
  src/entities/translate/ui/GuideRoutingButton.tsx
  src/features/sign-up/sign-up.types.ts
  src/features/sign-up/ui/funnel/CountryAccordion.tsx
  src/features/translate/ translate.types.ts
  src/features/translate/services/api/fetchGuideText.ts
  src/features/translate/translate.consts.ts
  src/features/translate/translate.types.ts
  src/features/translate/ui/RecordingIndicator.tsx
  src/features/translate/ui/guide/FunnelStepPlate.tsx
  src/features/translate/ui/guide/GuideAccordion.tsx
  src/features/translate/ui/guide/GuideFunnel.tsx
  src/pages/index.ts
  src/pages/translate/translate-guide.tsx
  src/pages/translate/translate.tsx
  src/shared/assets/common/closed.svg
  src/shared/assets/translate/guide-routing.svg
Labels: ✨ Feature

#20 [FE-54] 메인 병원 추천 구현
  src/features/main/ui/HospitalList.tsx
  src/features/search/ui/SearchList.tsx
  src/features/search/ui/SearchPreviewCard.tsx
  src/features/search/ui/Searchbar.tsx
  src/features/search/ui/detail/SearchDetailHeader.tsx
  src/features/search/ui/dropdown/DepartmentFilterDropdown.tsx
  src/features/search/ui/dropdown/SortDropdown.tsx
  src/pages/main/mainpage.tsx
  src/pages/search/search.tsx
  src/shared/components/skeleton/Skeleton.tsx
  src/shared/mock/index.tsx
Labels: ✨ Feature

#25 [FE-63] 통역 UI 및 기본 로직 구현
  src/app/routes/Routes.tsx
  src/entities/translate/ui/GuideProgressBar.tsx
  src/entities/translate/ui/GuideRoutingButton.tsx
  src/entities/translate/ui/MuteToggleButton.tsx
  src/entities/translate/ui/TranslateMicIndicator.tsx
  src/features/translate/ui/FinishTranslationModal.tsx
  src/features/translate/ui/TranslateController.tsx
  src/features/translate/ui/TranslateSessionView.tsx
  src/features/translate/ui/TranslateStarter.tsx
  src/features/translate/ui/guide/FunnelStepPlate.tsx
  src/features/translate/ui/guide/GuideFunnelModal.tsx
  src/pages/index.ts
  src/pages/translate/translate-finish.tsx
  src/pages/translate/translate-guide.tsx
  src/pages/translate/translate.tsx
  src/shared/assets/translate/mic-off.svg
  src/shared/assets/translate/translate-finish.svg
  src/shared/components/modal/Modal.tsx
Labels: ✨ Feature

#28 [FE-69] 첫 화면 렌더링 버그, 리다이렉트 버그 수정
  src/app/providers/AuthGuard.tsx
  src/app/providers/index.ts
  src/app/routes/Routes.tsx
  src/features/search/services/api/searchInstance.ts
  src/pages/map/map.tsx
Labels: 🐞 BugFix

#29 플로팅 버튼, 통역 UI 및 API, 빈 화면 렌더링 버그 수정 [develop -> main]
  src/app/providers/AuthGuard.tsx
  src/app/providers/index.ts
  src/app/routes/Routes.tsx
  src/entities/translate/ui/GuideProgressBar.tsx
  src/entities/translate/ui/GuideRoutingButton.tsx
  src/entities/translate/ui/MuteToggleButton.tsx
  src/entities/translate/ui/TranslateMicIndicator.tsx
  src/features/main/ui/HospitalList.tsx
  src/features/search/services/api/searchInstance.ts
  src/features/search/ui/SearchList.tsx
  src/features/search/ui/SearchPreviewCard.tsx
  src/features/search/ui/Searchbar.tsx
  src/features/search/ui/detail/SearchDetailHeader.tsx
  src/features/search/ui/dropdown/DepartmentFilterDropdown.tsx
  src/features/search/ui/dropdown/SortDropdown.tsx
  src/features/sign-up/sign-up.types.ts
  src/features/sign-up/ui/funnel/CountryAccordion.tsx
  src/features/translate/ translate.types.ts
  src/features/translate/services/api/fetchGuideText.ts
  src/features/translate/translate.consts.ts
  src/features/translate/translate.types.ts
  src/features/translate/ui/FinishTranslationModal.tsx
  src/features/translate/ui/RecordingIndicator.tsx
  src/features/translate/ui/TranslateController.tsx
  src/features/translate/ui/TranslateSessionView.tsx
  src/features/translate/ui/TranslateStarter.tsx
  src/features/translate/ui/guide/FunnelStepPlate.tsx
  src/features/translate/ui/guide/GuideAccordion.tsx
  src/features/translate/ui/guide/GuideFunnel.tsx
  src/features/translate/ui/guide/GuideFunnelModal.tsx
  src/pages/index.ts
  src/pages/main/mainpage.tsx
  src/pages/map/map.tsx
  src/pages/search/search.tsx
  src/pages/translate/translate-finish.tsx
  src/pages/translate/translate.tsx
  src/shared/assets/common/closed.svg
  src/shared/assets/home/CreateDiagnosis.svg
  src/shared/assets/records/NewButton.svg
  src/shared/assets/search/MapButton.svg
  src/shared/assets/translate/guide-routing.svg
  src/shared/assets/translate/mic-off.svg
  src/shared/assets/translate/translate-finish.svg
  src/shared/components/button/FloatingButton.tsx
  src/shared/components/modal/Modal.tsx
  src/shared/components/skeleton/Skeleton.tsx
  src/shared/mock/index.tsx
Labels: :earth_asia: Deploy

#26 [FE-55] Guide 페이지 구현
  src/app/routes/Routes.tsx
  src/features/main/guide.type.ts
  src/features/main/lib/useGuide.ts
  src/features/main/lib/useGuideCategories.ts
  src/features/main/service/guideApi.ts
  src/features/main/service/guideAtoms.ts
  src/features/main/ui/GuideCategories.tsx
  src/features/main/ui/GuideQuestions.tsx
  src/features/main/ui/HomeActionButton.tsx
  src/pages/index.ts
  src/pages/main/guide/guide-list.tsx
  src/pages/main/guide/guide.tsx
  src/pages/main/mainpage.tsx
  src/shared/api/languageApi.ts
  src/shared/assets/common/arrow.svg
  src/shared/services/languageCodeAtom.ts
Labels: ✨ Feature

#27 [FE-67] 자가진단표 알고리즘 및 추천 기능 커스텀훅 구현
  src/features/diagnosis/diagnosis.type.ts
  src/features/diagnosis/lib/diagnosis-algorithm/useAlgorithm.ts
  src/features/diagnosis/lib/diagnosis-algorithm/useConditions.ts
  src/features/diagnosis/lib/diagnosis-algorithm/useSymptoms.ts
  src/features/diagnosis/lib/diagnosis-algorithm/useSystems.ts
  src/features/diagnosis/lib/useRecommend.ts
  src/features/diagnosis/lib/useSelectedSymptoms.ts
  src/features/diagnosis/service/api/algorithmApi.ts
  src/features/diagnosis/service/api/diagnosisApi.ts
  src/features/diagnosis/service/api/index.ts
  src/features/diagnosis/service/api/recommendApi.ts
  src/features/diagnosis/ui/SelectedSymptoms.tsx
  src/features/diagnosis/ui/pages/StepFive.tsx
  src/features/diagnosis/ui/pages/StepFour.tsx
  src/features/diagnosis/ui/pages/StepThree.tsx
  src/pages/main/self-diagnosis/self-diagnosis.tsx
Labels: ✨ Feature

#24 [FE-42] 마이페이지 UI구현
  src/app/routes/Routes.tsx
  src/features/mypage/ui/Action.tsx
  src/features/mypage/ui/Bottom.tsx
  src/features/mypage/ui/CountryAccordionEdit.tsx
  src/features/mypage/ui/EditForm.tsx
  src/features/mypage/ui/EditHeader.tsx
  src/features/mypage/ui/EditMain.tsx
  src/features/mypage/ui/GenderSelect.tsx
  src/features/mypage/ui/Header.tsx
  src/features/mypage/ui/Main.tsx
  src/pages/mypage/edit-profile.tsx
  src/pages/mypage/mypage.tsx
  src/shared/assets/mypage/camera.svg
  src/shared/assets/mypage/favorite.svg
  src/shared/assets/mypage/like.svg
  src/shared/assets/mypage/option.svg
  src/shared/assets/mypage/profile.svg
  src/shared/assets/mypage/review.svg
Labels: ✨ Feature

#31 [FE-61] 마이페이지 API 구현
  src/features/mypage/MyPage.constants.ts
  src/features/mypage/service/MyPageApi.ts
  src/features/mypage/ui/CountryAccordionEdit.tsx
  src/features/mypage/ui/EditForm.tsx
  src/features/mypage/ui/EditMain.tsx
  src/features/mypage/ui/GenderSelect.tsx
  src/features/mypage/ui/Main.tsx
  src/shared/api/apiRequest.ts
  src/shared/types/api.types.ts
Labels: ✨ Feature

#23 [FE-41] 기록페이지 API구현
  src/app/routes/Routes.tsx
  src/features/records/consts/healthConstants.ts
  src/features/records/consts/medicalConstants.ts
  src/features/records/lib/BloodForm.ts
  src/features/records/lib/DateForm.ts
  src/features/records/service/healthDataApi.ts
  src/features/records/service/medicalDataApi.ts
  src/features/records/ui/BloodPressurePart.tsx
  src/features/records/ui/BloodSugarPart.tsx
  src/features/records/ui/DateSelection.tsx
  src/features/records/ui/HealthEditData.tsx
  src/features/records/ui/HealthStatusAddData.tsx
  src/features/records/ui/HealthStatusData.tsx
  src/features/records/ui/HealthStatusDetails.tsx
  src/features/records/ui/MainDetail.tsx
  src/features/records/ui/MedicalAddData.tsx
  src/features/records/ui/MedicalEditData.tsx
  src/features/records/ui/MedicalRecordData.tsx
  src/features/records/ui/MedicalRecordDetails.tsx
  src/features/records/ui/MedicineHistoryPart.tsx
  src/features/translate/translate.types.ts
  src/pages/records/healthstatus-add.tsx
  src/pages/records/healthstatus-edit.tsx
  src/pages/records/healthstatus-record-list.tsx
  src/pages/records/healthstatus.tsx
  src/pages/records/medicalrecord-add.tsx
  src/pages/records/medicalrecord-edit.tsx
  src/pages/records/medicalrecord-list.tsx
  src/pages/records/medicalrecord.tsx
  src/pages/records/records.tsx
  src/shared/api/apiRequest.ts
  src/shared/assets/common/delete-icon.svg
  src/shared/assets/records/diagnosisMain.svg
  src/shared/assets/records/healthMain.svg
  src/shared/assets/records/medicalMain.svg
  src/shared/types/api.types.ts
Labels: ✨ Feature

#34 [FE-71] 검색 API 연동
  src/app/routes/Routes.tsx
  src/entities/search/ui/CategoryTag.tsx
  src/features/map/map.types.ts
  src/features/search/lib/getDistanceInMeters.ts
  src/features/search/search.consts.ts
  src/features/search/search.types.ts
  src/features/search/services/api/searcApi.ts
  src/features/search/services/api/searchInstance.ts
  src/features/search/services/api/searchQuery.ts
  src/features/search/services/api/textSearchApi.ts
  src/features/search/services/hooks/useSearch.ts
  src/features/search/services/searchDetailPlaceQuery.ts
  src/features/search/services/store/filterAtom.ts
  src/features/search/services/store/searchQueryAtom.ts
  src/features/search/services/useNearbySearch.ts
  src/features/search/services/useTextSearch.ts
  src/features/search/types/department.types.ts
  src/features/search/types/search.types.ts
  src/features/search/ui/NoSearchResults.tsx
  src/features/search/ui/SearchList.tsx
  src/features/search/ui/SearchPreviewCard.tsx
  src/features/search/ui/Searchbar.tsx
  src/features/search/ui/detail/ContactFavoritePanel.tsx
  src/features/search/ui/detail/SearchDetailHeader.tsx
  src/features/search/ui/detail/SearchDetailInfo.tsx
  src/features/search/ui/dropdown/DepartmentFilterDropdown.tsx
  src/features/search/ui/dropdown/SortDropdown.tsx
  src/pages/main/mainpage.tsx
  src/pages/search/search-detail.tsx
  src/pages/search/search.tsx
  src/shared/api/apiRequest.ts
  src/shared/assets/search/favorite.svg
  src/shared/assets/search/search.svg
  src/shared/consts/common.ts
  src/shared/lib/getCurrLocation.ts
  src/shared/services/useCurrLocation.ts
  src/shared/types/api.types.ts
  src/shared/types/common.ts
Labels: ✨ Feature

#33 [FE-72] 추천페이지 UI 및 Api 연동
  src/app/routes/Routes.tsx
  src/features/diagnosis/ui/DiagnosisHeader.tsx
  src/features/diagnosis/ui/ProgressBar.tsx
  src/features/main/ui/GuideCategories.tsx
  src/features/main/ui/GuideHeader.tsx
  src/pages/index.ts
  src/pages/main/self-diagnosis/RecommendPage.tsx
  src/shared/assets/common/location.png
  src/shared/components/overlay/LoadingOverlay.tsx
Labels: ✨ Feature

#37 [FE-74] 의료기록 UI 추가 및 버튼 위치 변경
  src/features/records/ui/HealthEditData.tsx
  src/features/records/ui/HealthStatusData.tsx
  src/features/records/ui/MedicalEditData.tsx
  src/features/records/ui/NoneRecord.tsx
  src/pages/records/medicalrecord-add.tsx
  src/pages/records/medicalrecord-list.tsx
  src/pages/records/self-diagnosis-list.tsx
  src/shared/assets/records/plus.svg
Labels: 🔨 Refactor

#41 [FE-70] 통역 컴포넌트 언마운트 시 종료
  src/features/translate/ui/TranslateController.tsx
Labels: ✨ Feature

#43 [FE-82] 중국 국적 선택란 추가
  src/features/mypage/MyPage.constants.ts
  src/features/sign-up/sign-up.constants.ts
Labels: ✨ Feature
