Repository OUCH-cs/CAPSTONE-PWA, pull requests merged in 2025-04, with the labels that each got.

#4 [FE-25] 아코디언 공통 컴포넌트 구현
  src/app/routes/Routes.tsx
  src/pages/auth/sign-up.tsx
  src/pages/mypage/mypage.tsx
  src/pages/test/test.tsx
  src/shared/api/apiRequest.ts
  src/shared/assets/common/arrow.svg
  src/shared/components/accordion/Accordion.tsx
  src/shared/components/accordion/Body.tsx
  src/shared/components/accordion/Header.tsx
  src/shared/components/accordion/Item.tsx
  src/shared/components/accordion/Trigger.tsx
  src/shared/components/accordion/index.ts
  src/shared/components/button/Button.tsx
  src/shared/components/modal/Modal.tsx
  src/shared/hooks/index.ts
  src/shared/lib/index.ts
  src/shared/lib/useAccordionContext.ts
  src/shared/lib/useAccordionToggle.ts
  src/shared/lib/useClickOutside.ts
  src/shared/lib/useToggle.ts
  src/shared/services/AccordionContext.tsx
  src/shared/services/index.ts
  src/shared/types/context.types.ts
  src/shared/types/index.ts
Labels: ✨ Feature, 🚧 Draft

#6 [FE-10] 로그인 UI 구현
  package.json
  src/app/providers/AccordionContext.tsx
  src/app/providers/AuthGuard.tsx
  src/app/providers/index.ts
  src/app/routes/Routes.tsx
  src/entities/auth/auth.types.ts
  src/entities/auth/ui/InputField.tsx
  src/features/sign-in/services/atoms/auth.atoms.ts
  src/features/sign-in/services/atoms/index.ts
  src/features/sign-in/ui/LoginForm.tsx
  src/pages/auth/sign-in.tsx
  src/shared/assets/common/Logo.tsx
  src/shared/assets/common/logo.svg
  src/shared/components/accordion/Accordion.tsx
  src/shared/components/base/TabBar.tsx
  src/shared/lib/useAccordionContext.ts
  src/shared/services/index.ts
  src/shared/types/components.types.ts
  yarn.lock
Labels: ✨ Feature

#8 머지 시 파일위치 충돌 해결 [FE-38-migration -> develop]
  package.json
  src/app/providers/AuthGuard.tsx
  src/app/providers/index.ts
  src/app/routes/Routes.tsx
  src/entities/auth/auth.types.ts
  src/entities/auth/ui/InputField.tsx
  src/features/sign-in/services/atoms/auth.atoms.ts
  src/features/sign-in/services/atoms/index.ts
  src/features/sign-in/ui/LoginForm.tsx
  src/pages/auth/sign-in.tsx
  src/shared/assets/common/Logo.tsx
  src/shared/assets/common/logo.svg
  src/shared/components/accordion/Accordion.tsx
  src/shared/components/base/TabBar.tsx
  src/shared/lib/useAccordionContext.ts
  src/shared/services/index.ts
  src/shared/types/components.types.ts
  yarn.lock
Labels: 🐞 BugFix

#9 [FE-38] 홈/ 자가진단표 UI 구현
  package.json
  src/app/main.tsx
  src/app/routes/Routes.tsx
  src/features/diagnosis/diagnosis.type.ts
  src/features/diagnosis/lib/chunkArray.ts
  src/features/diagnosis/lib/useFunnel.tsx
  src/features/diagnosis/lib/useProgress.tsx
  src/features/diagnosis/lib/useSelectedSymptoms.ts
  src/features/diagnosis/lib/useSymptomsList.ts
  src/features/diagnosis/service/selfDiagnosisAtoms.ts
  src/features/diagnosis/service/updateProgress.tsx
  src/features/diagnosis/ui/Funnel.tsx
  src/features/diagnosis/ui/PainLevelBar.tsx
  src/features/diagnosis/ui/ProgressBar.tsx
  src/features/diagnosis/ui/SelectDestination.tsx
  src/features/diagnosis/ui/SelectedSymptoms.tsx
  src/features/diagnosis/ui/SymptomsList.tsx
  src/features/diagnosis/ui/common/index.ts
  src/features/diagnosis/ui/pages/AddSymptomsPage.tsx
  src/features/diagnosis/ui/pages/StepFive.tsx
  src/features/diagnosis/ui/pages/StepFour.tsx
  src/features/diagnosis/ui/pages/StepOne.tsx
  src/features/diagnosis/ui/pages/StepThree.tsx
  src/features/diagnosis/ui/pages/StepTwo.tsx
  src/features/main/ui/DiagnosisCard.tsx
  src/features/main/ui/HomeActionButton.tsx
  src/features/main/ui/HospitalList.tsx
  src/features/main/ui/MainHeader.tsx
  src/pages/index.ts
  src/pages/main/main.tsx
  src/pages/main/mainpage.tsx
  src/pages/main/self-diagnosis/diagnosis-faq.tsx
  src/pages/main/self-diagnosis/self-diagnosis.tsx
  src/shared/assets/diagnosis/MinusButton.svg
  src/shared/assets/diagnosis/PlusButton.svg
  src/shared/assets/home/HomeCamera.svg
  src/shared/assets/home/HomeDiagnosis.tsx
  src/shared/assets/home/HomeGuide.svg
  src/shared/assets/home/HomeLocation.svg
  src/shared/assets/hospital/HospitalRate.svg
  src/shared/mock/index.tsx
  src/shared/styles/theme.ts
  tsconfig.app.json
  tsconfig.json
  yarn.lock
Labels: ✨ Feature

#7 [FE-6]의료기록 페이지 UI 마이그레이션
  package-lock.json
  package.json
  src/app/routes/Routes.tsx
  src/features/records/consts/healthConstants.ts
  src/features/records/consts/medicalConstants.ts
  src/features/records/ui/BloodPressurePart.tsx
  src/features/records/ui/BloodSugarPart.tsx
  src/features/records/ui/DateSelection.tsx
  src/features/records/ui/HealthStatusAddData.tsx
  src/features/records/ui/HealthStatusData.tsx
  src/features/records/ui/HealthStatusDetails.tsx
  src/features/records/ui/MedicalAddData.tsx
  src/features/records/ui/MedicalRecordData.tsx
  src/features/records/ui/MedicalRecordDetails.tsx
  src/features/records/ui/MedicineHistoryPart.tsx
  src/pages/records/healthstatus-add.tsx
  src/pages/records/healthstatus-record-list.tsx
  src/pages/records/healthstatus.tsx
  src/pages/records/medicalrecord-add.tsx
  src/pages/records/medicalrecord-list.tsx
  src/pages/records/medicalrecord.tsx
  src/pages/records/records.tsx
  src/shared/assets/common/backarrow.svg
  src/shared/assets/common/edit-icon.svg
  yarn.lock
Labels: ✨ Feature

#12 [FE-15] 회원가입 유효성 검사 로직 구현 및 API 연동
  index.html
  package.json
  src/entities/auth/auth.types.ts
  src/entities/auth/ui/InputField.tsx
  src/features/sign-up/lib/form.schema.ts
  src/features/sign-up/lib/getFunnelGuideLabel.ts
  src/features/sign-up/lib/useSignupForm.ts
  src/features/sign-up/sign-up.constants.ts
  src/features/sign-up/sign-up.types.ts
  src/features/sign-up/ui/funnel/CountryAccordion.tsx
  src/features/sign-up/ui/funnel/FunnelStepPlate.tsx
  src/features/sign-up/ui/funnel/GenderSelection.tsx
  src/features/sign-up/ui/funnel/SignupFunnel.tsx
  src/pages/translate/translate.tsx
  src/shared/api/apiRequest.ts
  src/shared/components/accordion/Item.tsx
  src/shared/components/funnel/FunnelStepPlate.tsx
  src/shared/styles/theme.ts
  src/shared/types/context.types.ts
  yarn.lock
Labels: ✨ Feature

#14 회원가입 / 로그인 로직 및 API 연동 [develop -> main]
  index.html
  package.json
  src/entities/auth/auth.types.ts
  src/entities/auth/lib/form.schema.ts
  src/entities/auth/ui/InputField.tsx
  src/features/sign-in/lib/tokenHandler.ts
  src/features/sign-in/lib/useSigninForm.ts
  src/features/sign-in/sign-in.constants.ts
  src/features/sign-in/sign-in.types.ts
  src/features/sign-in/ui/LoginForm.tsx
  src/features/sign-up/lib/getFunnelGuideLabel.ts
  src/features/sign-up/lib/useSignupForm.ts
  src/features/sign-up/sign-up.constants.ts
  src/features/sign-up/sign-up.types.ts
  src/features/sign-up/ui/funnel/CountryAccordion.tsx
  src/features/sign-up/ui/funnel/FunnelStepPlate.tsx
  src/features/sign-up/ui/funnel/GenderSelection.tsx
  src/features/sign-up/ui/funnel/SignupFunnel.tsx
  src/pages/translate/translate.tsx
  src/shared/api/apiRequest.ts
  src/shared/api/axiosInstance.ts
  src/shared/components/accordion/Item.tsx
  src/shared/components/funnel/FunnelStepPlate.tsx
  src/shared/styles/theme.ts
  src/shared/types/context.types.ts
  yarn.lock
Labels: :earth_asia: Deploy

#15 [FE-12] 백엔드 회원가입 언어, 국적 데이터 스키마 변경사항 반영
  src/entities/auth/lib/form.schema.ts
  src/features/sign-up/lib/getFunnelGuideLabel.ts
  src/features/sign-up/sign-up.constants.ts
  src/features/sign-up/ui/funnel/CountryAccordion.tsx
  src/features/sign-up/ui/funnel/FunnelStepPlate.tsx
  src/features/sign-up/ui/funnel/SignupFunnel.tsx
Labels: 🐞 BugFix

#16 [FE-12] 백엔드 회원가입 언어, 국적 데이터 스키마 변경사항 반영 [develop -> main]
  src/entities/auth/lib/form.schema.ts
  src/features/sign-up/lib/getFunnelGuideLabel.ts
  src/features/sign-up/sign-up.constants.ts
  src/features/sign-up/ui/funnel/CountryAccordion.tsx
  src/features/sign-up/ui/funnel/FunnelStepPlate.tsx
  src/features/sign-up/ui/funnel/SignupFunnel.tsx
Labels: :earth_asia: Deploy
